gfcli:
  gen:
    dao:
      - link: "mysql:root:NfySZsRBGrNGGhTJ@tcp(36.255.222.166:3306)/happy_poker"
        tables: "player"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true

database:
  database.logger:
    Level: "all"
    Stdout: true
    CtxKeys: ["Trace-Id"]
  default:
    link: "mysql:root:NfySZsRBGrNGGhTJ@tcp(36.255.222.166:3306)/happy_poker"
    debug: true